const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "GETCH_POSITION_FAILED",

  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROOLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

  CREATE_NEW_USER_START: "CREATE_NEW_USER_START",
  CREATE_NEW_USER_SUCCESS: "CREATE_NEW_USER_SUCCESS",
  CREATE_NEW_USER_FAILED: "CREATE_NEW_USER_FAILED",

  GET_ALL_USER_START: "GET_ALL_USER_START",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_FAILED: "GET_ALL_USER_FAILED",

  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  //LOAD TOP OUTSTANDING DOCTOR
  GET_OUTSTANDING_DOCTOR_SUCCESS: "GET_OUTSTANDING_DOCTOR_SUCCESS",
  GET_OUTSTANDING_DOCTOR_FAILED: "GET_OUTSTANDING_DOCTOR_FAILED",

  //FETCH ALL DOCTOR
  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAILED: "FETCH_ALL_DOCTOR_FAILED",

  // CREATE DETAIL DOCTOR
  CREATE_DETAIL_DOCTOR_SUCCESS: "CREATE_DETAIL_DOCTOR_SUCCESS",
  CREATE_DETAIL_DOCTOR_FAILED: "CREATE_DETAIL_DOCTOR_FAILED",

  //GET DETAIL DOCTOR

  GET_DETAIL_DOCTOR_SUCCESS: "GET_DETAIL_DOCTOR_SUCCESS",
  GET_DETAIL_DOCTOR_FAILED: "GET_DETAIL_DOCTOR_FAILED",

  // EDIT DETAIL DOCTOR
  EDIT_DETAIL_DOCTOR_SUCCESS: "EDIT_DETAIL_DOCTOR_SUCCESS",
  EDIT_DETAIL_DOCTOR_FAILED: "EDIT_DETAIL_DOCTOR_FAILED",
});

export default actionTypes;
